services:
  backend:
    build: .
    container_name: blogs-api
    env_file: ".env"
    ports:
      - 4000:${PORT}
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime && 
      echo ${TIME_ZONE} > /etc/timezone && npm run dev"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres_blog
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres_data:
